### ISSUE TITLE
Planning an SICP Study Group

### ISSUE THREAD

**Issue by jdantonio** [AkronCodeClub/sicp-study-group#1]
Back in September when we first began discussing an online course study group, Structure and Interpretation of Computer Programs (SICP) received the second-highest number of votes. Now that we are nearing the end of the Haskell course (which, sadly, didn't meet the expectations of most involved), it's time we revisit SICP.

Many may remember that our main concern back in September was logistical. The edX course we signed up for had a defined start date, defined end date, defined deliverables, and set of hard due dates. SICP lacks all of these. One of the main frustrations we've encountered with the edX course is the lack of code deliverables. Virtually all the assignments are multiple choice tests. With no code to share there are no opportunities for pair programming and no opportunities to discuss our solutions.
## Meeting

Those who are interested and available are invited to join us **6:00 PM** on **Dec. 15, 2014** at the [Nervous Dog Coffee Bar](http://nervousdog.com/) located in **West Akron** at [1530 West Market Street, Akron OH 44313](https://www.google.com/maps/place/1530+W+Market+St,+Akron,+OH+44313/data=!4m2!3m1!1s0x8830d709551a2f0d:0x15fefceab0433372?sa=X&ei=rPF9VNWjLYudyASPm4DQBg&ved=0CB8Q8gEwAA). Please RSVP through [meetup.com](http://www.meetup.com/AkronCodeClub/events/219022400/).

Those unable to attend our initial planning meeting are welcome to participate in the study group and also participate in this online discussion.
## Logistics

_Objective: How do we structure a study group around the SICP book?_

To be successful we likely must solve most, if not all, of the following logistical issues:
- Start date and end date
- Schedule for readings, assignments, and meetings
- Expectations for what will be done _during_ meetings
- Expectations for what will be done _prior to_ meetings
- Expectations for those _unable to attend_ one or more meetings
## Things to Think About

Random things we should take into consideration:
- Strictly follow the book, strictly follow the online course, or some amalgamation of the two?
- What language(s) will we use? (The book and course use MIT Scheme)
- How do we integrate the activities of those who can meet _in person_ with those who want/need to work online?
- What code do we write and share? Some or all of the exercises in the book? The projects from the online course? All the above?
- What do we want to do _at_ the meetings? Work through the assignments together or discuss assignments we've already completed?
- Should we attempt to tackle the _entire_ book/course or should we start with a subset, such as just the first chapter?
## Resources
- [SICP book site](http://mitpress.mit.edu/books/structure-and-interpretation-computer-programs) at MIT Press
- [SICP book companion site](http://mitpress.mit.edu/sicp/) with additional resources
- [2005 SICP course at MIT](http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-001-structure-and-interpretation-of-computer-programs-spring-2005/) hosted on MIT OpenCourseWare
- [Seattle.rb SICP study group](https://github.com/SeaRbSg/SICP) repo on GitHub
- [Seattle.rb presentation](https://www.youtube.com/watch?v=AK-gVWh_vZ8) from MountainWest RubyConf 2014 in which they share their "recipe for our user group and study group"

**Comment by grantwinney** [comment]
Hey Jerry. It's been awhile but looks like it hasn't started yet. I'm in.
