### ISSUE TITLE
Configuring Emacs for SICP

### ISSUE THREAD

**Issue by pzula** [AkronCodeClub/sicp-study-group#12]
Hi everyone!

I took on the challenge of figuring out how to use and set up Emacs for using MIT-Scheme for the purpose of our SICP study group. As a complete newbie, (and a strong vim user), I minimally configured it so that I have full access to my vim keybindings, but have all the goodness of the Emacs/Scheme integration. I wrote a step-by-step about it here, if anyone else wants to give it a try:

http://www.codeadventurer.com/2014/12/21/sicp-and-emacs-for-the-vim-user

**Comment by jdantonio** [comment]
Closing to help cleanup the issues page.
