### ISSUE TITLE
Interactive online Scheme REPL

### ISSUE THREAD

**Issue by jdantonio** [AkronCodeClub/sicp-study-group#13]
While working on JavaScript tutorials I found a really cool online [Scheme interpreter](http://repl.it/languages/Scheme). (Actually, the service supports [multiple languages](http://repl.it/languages), which is even more cool!) For those struggling with editor/IDE difficulties, the online REPL may be a solution. I plan to give it a try myself.

**Comment by gvoudzon** [comment]
Am I doing something wrong?
When I C & P the source code from Exercise 1.1,  it only seems to execute the code from the last expression.   Is that the way that the Scheme Interpreter web site is supposed to work?   Or am I doing something wrong here?

**Comment by gvoudzon** [comment]
Obviously,   my atoms are being scattered all over the place as I am beaming down...   :-/
