### ISSUE TITLE
Problem with Panera

### ISSUE THREAD

**Issue by jdantonio** [AkronCodeClub/sicp-study-group#18]
I talked to the powers-that-be at Panera only to discover that it *costs actual money* to reserve the back room. WTH? A *for-profit* business trying to make money? Isn't this the Internet-era? Isn't everything supposed to be free?

Seriously, though, there is an actual cost to reserving the back room. The group has to commit to collectively spending $50 on food and drink during the two-hour meeting. If enough people attend each meetup and everyone plans to buy dinner and/or a hot drink it's probably not a big deal. If 10 people attend each person only has to spend $5. The issue for me is the *commitment*.

Since this is new for it's a risk to commit to Panera. I've given them a list of dates and my contact information so it's still an option if we want to make the commitment. If not, we need a Plan B. Here are a couple of thoughts:

* We can meet at Panera and pull a bunch of tables together like we did a few weeks ago
* There is free wi-fi at Winking Lizard, and they server beer (though that may not be a good thing)
* Acme has "free" community rooms but I don't know the details yet (I've left a voicemail and I'm waiting for them to call back)
* VHT's offices are available (although I--personally--would rather meet elsewhere if possible)
* We meet in a different part of town (downtown, for example) that gives us other options

Thoughts?

**Comment by thoolihan** [comment]
Just a thought, but the Fairlawn Branch of the Akron Library is close by. I called and they do have a meeting room that is open as long as the event is free and open to the public. They would have space and wifi, and the room can be reserved. While we meet all the criteria, the only issues I see is open the public. I like the idea and wouldn't want to discourage anyone from attending, but unless they join from the start it is an advanced topic to wander into and expect to make traction. 

If you are interested in confirming available dates, you can reach them at 330 666 4888. Branch manager is Jane Scott. 

Note they have a clause on no classes, but I explained that this was a study group and not the class itself, and that the source material is freely available. They did not seem to think the "class" clause would be an issue.

**Comment by RickBacci** [comment]
I called the Barnes & Noble right near there. They do have a table near the front of the store that could possibly fit 10 people. There is also the cafe. They did say that they may do something else with the space in the future.

@jdantonio Is it $50 or $100 commitment for Panera? You said $10 a person and i assume you meant $5. I would say the Lizard would be fine as a backup.

**Comment by jdantonio** [comment]
@RickBacci Panera is $50 for the group. I updated my original post to correct my math error.

@thoolihan I've never been to that branch of the library but it sounds like a good option. I'll check it out this weekend.

**Comment by jonknapp** [comment]
I'm up for any meeting location, even if there's a small cost.  Libraries can be nice though, used one for a meetup once.

**Comment by jdantonio** [comment]
I've been planning to check out the library but I caught a bad chest cold and haven't been out of the house in a few days. We should endeavor to decide before next Monday so that we can announce the location at the regular Code Club meetup.

**Comment by jonknapp** [comment]
I'm comfortable saying Panera (if we have the people).  Otherwise, I can
talk to TechLab (downtown Akron and free) about nabbing some space.

Jonathan Knapp
Coffee and Code, LLC
www.coffeeandcode.com
330.249.1007

**Comment by jdantonio** [comment]
@jonknapp Please talk to TechLab. It's always good to have options.

**Comment by jonknapp** [comment]
We got TechLab locked down.  We can go somewhere else if we'd like, we just need to let Nick know so he's not waiting for us.

**Comment by jonknapp** [comment]
We got it locked down for the 19th. We can adjust somewhere else if needed.

**Comment by jdantonio** [comment]
Every day (but one) that we wanted, the library was already booked. I've booked Panera for now and we'll revisit later if necessary.
