### ISSUE TITLE
No InstallFest on January 5th

### ISSUE THREAD

**Issue by jdantonio** [AkronCodeClub/sicp-study-group#19]
The gentleman who attended the planning meeting and volunteered to host an InstallFest on Monday is MIA. He has not checked in with this GitHub repo/group nor has he responded to messages in Meetup.com. Unfortunately, this means we will not be able to hold the InstallFest meeting we were hoping to have on Monday.

**Comment by jonknapp** [comment]
shame about the install fest.  guess we can close this issue for now.
