### ISSUE TITLE
Should we cancel tonight (Feb. 2)? -- Inclement Weather!

### ISSUE THREAD

**Issue by jdantonio** [AkronCodeClub/sicp-study-group#22]
The weather is really, *really* bad. Should we cancel tonight and continue working online until the next meetup?

**Comment by eyston** [comment]
The weather is going to keep me away :/

**Comment by jonknapp** [comment]
I can go either way. I got to downtown Akron without much trouble, but not sure what's going to happen during the day (or late afternoon/evening).

@RickBacci if the weather is bad, no reason to make you drive down from Cle to meet later today. Let me know what you are thinking.

**Comment by vht-hfenton** [comment]
I am not sure how the rest of the day will go with the weather but as a precaution, lets cancel to be on the safe side.

**Comment by tezyn** [comment]
Probably the safe decision to make 

Joshua

**Comment by rpottsoh** [comment]
@jdantonio.  I’m still up for meeting this evening.  Roads are fine at the moment, however looks like high chances for more snow during the day.  I had no problems during my morning commute from Bath to North Canton, sunny outside at the moment.  Looks like lake effect potential so points north of Akron could be worse….

 

Count me in.

 

Ryan

**Comment by RickBacci** [comment]
@jonknapp Pretty positive that I'll make it to work on our project. I snow plowed for around 20 years so the snow doesn't bother me. 

I'm good with whatever everyone decides as far as the sicp class.

**Comment by grantwinney** [comment]
I can go either way. Looks like the snow is pretty much done down this way
in Aurora (flurries, but not heavy), and the forecast isn't calling for
much more, but if anyone's driving through the Snowbelt, I know how fun
that can be...

**Comment by jdantonio** [comment]
It's snowing sideways at the VHT office (down the street from Panera). It's a heavy, steady snowfall that's showing no signs of stopping.

**Comment by grantwinney** [comment]
Might as well cancel and try again in a couple weeks. Maybe we'll be out of
the single digits by then too. (That doesn't seem like too much to ask.)

**Comment by jdantonio** [comment]
The weather is still really bad down here near Panera so a number of people said they can't make it. So we're officially canceling--which means we won't have to pay Panera.

Please feel free to get together with other members of the group if so inclined. We don't need a formal meetup for members to get together!

I've canceled the room reservation at Panera but that doesn't mean people can't still meet there. It sounds like Jon and Rick may be getting together in downtown Akron so they may still be interested in meeting. I'll probably try to get a small group together at the Nervous Dog later this week, and others can do the same. Plus, we can still share code online.

That's the beauty of GitHub--we can collaborate even when we can't get together.

**Comment by rpottsoh** [comment]
I'm up for getting together with whomever later in the week.  Since we've canceled my wife has accepted an invitation to go to tonight's CAVS game so this evening is out for me.
